### ISSUE TITLE
BSOD on Windows 10

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#111]
Here's a chat I had with Extravert-ir regarding the BSOD I had on Windows 10:

3:51 <Zero3K> oh, another issue I have with the BTRFS driver which is unrelated to ReactOS is as follows
3:52 <Zero3K> I have two VHDs that I made with VirtualBox
3:52 <Zero3K> one is BTRFS and the other is FAT32
3:52 <Zero3K> I mounted both drives via Simple VHD Manager
3:52 <Zero3K> and copied a file/files from the BTRFS to the FAT32 one
3:52 <Zero3K> then I unmounted both at the same time
3:53 <Zero3K> when I did that, it BSOD'd on me with a FAT_FILE_SYSTEM error
3:53 <Zero3K> It also probably happens when copying from the FAT32 to the BTRFS
3:54 <extravert34> this happens on windows?
3:55 <Zero3K> yes
3:55 <Zero3K> Windows 10

You can download the minidumps regarding the BSOD at the following links:

https://u.teknik.io/4E4Wv.dmp
https://u.teknik.io/fT27W.dmp

**Comment by maharmstone** [comment]
Looks to me like Windows is getting confused, and passing messages for the Btrfs FS to the FAT driver...

**Comment by Zero3K** [comment]
That's what I think too. Hopefully its fixable.

**Comment by maharmstone** [comment]
This should be fixed by https://github.com/maharmstone/btrfs/commit/1d99ee3129453cd43f717b3efa1c6a2fc29cf177.

We were clearing the "mounted" flag on the device object even if there were still files open. Thinking it was unmounted, Windows was passing it to FAT to mount. Because FAT had control of it, it was receiving the requests to close the last few files, resulting in the crash.
