### ISSUE TITLE
BSOD happening when mounting and unmounting multiple VHDs

### ISSUE THREAD

**Issue by Zero3K** [maharmstone/btrfs#132]
I had a BSOD happen when I used Simple VHD Manager (https://www.sordum.org/8705/simple-vhd-manager-v1-3/) to mount and unmount 4 VHDs (3 of them are formatted as BTRFS and the last one is formatted as NTFS). It was an IRQL_NOT_LESS_OR_EQUAL BSOD. The Minidump is attached as a ZIP archive.

[112518-6203-01.zip](https://github.com/maharmstone/btrfs/files/2613213/112518-6203-01.zip)

**Comment by maharmstone** [comment]
Is this using the latest release, or the master? There's some fixes regarding VHDs that haven't been released yet, so unless you're compiling it yourself please hold off from filing VHD-related bugs for now.

**Comment by Zero3K** [comment]
I'm using the master. So, the issue might've already been fixed?

**Comment by Zero3K** [comment]
Has it been fixed?

**Comment by suprimex** [comment]
cloned and compiled at 13/May/2019 by yourself,  tried to attach simple VHD,  at once got BSOD SYSTEM_THREAD_EXCEPTION_NOT_HANDLED .  


Dump File | Crash Time | Bug Check String | Bug Check Code | Parameter 1 | Parameter 2 | Parameter 3 | Parameter 4 | Caused By Driver | Caused By Address | File Description | Product Name | Company | File Version | Processor | Crash Address | Stack Address 1 | Stack Address 2 | Stack Address 3 | Computer Name | Full Path | Processors Count | Major Version | Minor Version | Dump File Size | Dump File Time
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
051319-42640-01.dmp | 13.05.2019 13:42:38 | SYSTEM_THREAD_EXCEPTION_NOT_HANDLED | 0x1000007e | ffffffff`c0000005 | fffff80f`4bebe4a6 | ffffdd01`30b92948 | ffffdd01`30b92190 | FsDepends.sys | FsDepends.sys+4100 | File System Dependency Manager Mini Filter Driver | Microsoft® Windows® Operating System | Microsoft Corporation | 10.0.17134.1 (WinBuild.160101.0800) | x64 | btrfs.sys+e4a6 |   |   |   |   | C:\WINDOWS\Minidump\051319-42640-01.dmp | 4 | 15 | 17134 | 678 444 | 13.05.2019 13:43:55

**Comment by maharmstone** [comment]
Sorry, are you saying that you're using the release binaries that I compiled, or that you've compiled them yourself? If the latter, can you please send me a minidump using the release binaries?

**Comment by suprimex** [comment]
sorry, I mean I compiled by myself.   this minidump is not accessible anymore,  but I suppose it is easily repeatable.  Windows version 1803  OS build 17134.706.

**Comment by maharmstone** [comment]
Please send me a minidump using the release binaries, and I'll have a look at it.

**Comment by Zero3K** [comment]
I don't have that BSOD in Windows 7.

**Comment by Zero3K** [comment]
I am closing this issue since the BSOD I mentioned in the beginning of it has been fixed.
