### ISSUE TITLE
Accessing files with special reserved symbols names

### ISSUE THREAD

**Issue by BloodyAltair** [maharmstone/btrfs#151]
Is it possible to access file, named `10.8.22.138:3333.gpg` on btrfs volume? Currently i can see this file in windows explorer window, but i can't read it with any other program

**Comment by maharmstone** [comment]
Probably not. From Windows' point of view, you're asking it to read the stream `3333.gpg` of file `10.8.22.138`.

**Comment by ale5000-git** [comment]
@BloodyAltair: I haven't tried but maybe you can try access it with [busybox-w32](https://frippery.org/busybox/) that is born under Linux so it may have less limitations.

**Comment by BloodyAltair** [comment]
@ale5000-git Neither busybox, nor WSL bash can access those files. Seems like we need more low level tool. It would be great, if we have such CLI tool

**Comment by rmyorston** [comment]
Although busybox-w32 comes from the Linux world it uses the Windows API, so filenames are interpreted according to Windows conventions.

A couple of ill-informed thoughts based on no knowledge of btrfs or Windows file streams:
- If the name ```10.8.22.138:3333.gpg``` represents a stream associated with the file ```10.8.22.138```, does the name ```10.8.22.138``` represent the file itself? (And what happens if there's more than one file with a name like that?)
- Would it be possible to make a hard link to the file that has a valid name? Presumably this would have to be done with the filesystem mounted on a platform that doesn't treat the colon as special.

**Comment by rmyorston** [comment]
OK, I should have thought harder about that: if Windows asks btrfs for a file called ```10.2.22.138``` btrfs will, of course, tell it there's no such file. (Unless there is, but that's a different matter.)

**Comment by ale5000-git** [comment]
According to Wikipedia for NTFS:
```
Paths can be up to 32,000 characters.
Forbids the use of characters in range 1-31 (0x01-0x1F) and characters " * / : < > ? \ | unless the name is flagged as being in the Posix namespace. NTFS allows each path component (directory or filename) to be 255 characters long
```

So using the Posix namespace would remove the restrictions.

**Comment by maharmstone** [comment]
Namespaces appear to be a feature of NTFS - it's not part of the NT kernel.

I'm going to close this issue, as it's not something we can overcome without writing a parallel API - and I'm not going to do that unless there's a compelling reason.

**Comment by PythonNut** [comment]
There may be a much simpler solution for the specific case of WSL now. Since [WSL 17101](https://github.com/MicrosoftDocs/WSL/releases/tag/17101), paths with illegal characters are re-encoded using private Unicode characters. (For example, the colon is encoded as 0xf03a.) This applies even for BTRFS (try it!), so one could easily add support simply by reversing this mapping.

**Comment by ale5000-git** [comment]
@maharmstone: Is it possible to support this "encoding" for all forbidden characters?

**Comment by DocMAX** [comment]
Is there a chance to let winbtrfs translate them so that i can delete or rename such files?
