### ISSUE TITLE
Decompress an entire Btrfs volume

### ISSUE THREAD

**Issue by Starz0r** [maharmstone/btrfs#163]
Apparently Zstd is enabled on Btrfs volumes by default, and I did not know this. The default setting is very aggressive, and can cause some pretty bad performance regressions in games (startup times, intelligent file loading, etc...). There seems to be a global setting for Zstd compression, but it only applies to rewritten or new files, it's not retroactive. So I have two questions.

1. Is it possible to know how large the actual volume is before decompressing? (Or how large it will be after decompressing).

2. Is it even possible to decompress the entire volume sanely? (referencing #68 & #69)

**Comment by Atemu** [comment]
>Apparently Zstd is enabled on Btrfs volumes by default

It's a good idea to do it since lower ZSTD levels cost almost no resources and should actually speed things up on anything but NVMe SSDs but I don't think any compression is enabled by default. How did you come to this conclusion?

>The default setting is very aggressive, and can cause some pretty bad performance regressions in games

Which ZSTD level is active for your btrfs in the mount options?

>Is it possible to know how large the actual volume is before decompressing? (Or how large it will be after decompressing).

Yes, there should be a breakdown of how much data is used by which compression algorithm and how much they compressed it in the btrfs tab for files and directories/subvols (see #94) . I'm not sure if it's in the btrfs tab for the whole filesystem (pretty sure it is not) but you can select everything in your root subvolume and right click it to get the total amount.

>Is it even possible to decompress the entire volume sanely? (referencing #68 & #69)

Those bugs are not reproducible for me.

Though uncompressing might prove difficult, defragmentation is not implemented in BTRFS on Windows yet (#137) and on Linux it can only be used to switch between compression algorithms and not uncompress as far as I'm aware.

**Comment by Starz0r** [comment]
@Atemu It seems that I didn't read all the registry keys and that `ZlibLevel` and `ZstdLevel` are both set, but `Compress`, `CompressForce`, and `CompressType`, are all zeroed out.

I was trying to rationalize why performance may be so bad in some games when using this driver, that maybe the Zlib or ZStd compression is getting in the way of loading files on the fly. That seems to not be the case. I'd close this issue, but I need to first confirm that it's impossible to decompress a Btrfs volume with compression enabled on it. In case a user actually wants the answer to that question.

**Comment by Fuzen-py** [comment]
Old issue but, it’s possible to do this with Linux using the btrfs’ defrag command

**Comment by maharmstone** [comment]
Closing old issues
