### ISSUE TITLE
btrfs 1.3/1.4 BSOD with NO_MORE_IRP_STACK_LOCATIONS

### ISSUE THREAD

**Issue by mgdde** [maharmstone/btrfs#186]
Windows 10 Pro 1903 DE, all availlable patches installed
External (USB 3) disk formatted with btrfs under Linux. Works w/o apparent problems. After accessing several 1000 files (read and write) eventually I get a BSOD claiming that important information are collected and then a reboot.

The progress indicator never leaves 0%. The Errorcode is NO_MORE_IRP_STACK_LOCATIONS.
This happened once with 1.3 and once with 1.4.

The usecase is this:
My collection of audio files (mp3, m4a, ogg, ...) is on an external 2TB drive formatted with btrfs under Linux. The collection is something like 60000 files in a hirarchy of several 1000 directories. On Windows I'm accessing the collection with Traktor Pro (DJ software from Native Instruments) and start analyzing the collection. This takes a day or two and doesn't finish but eventually crashes. Doing the analyze in chunks of 5000 files seems to work. During the analysis the audio files are read and the result is added as metadata to the files.

What can/should I do to further debug this problem?

**Comment by MegaZeroX10** [comment]
Do the new commits fix this issue?

**Comment by mgdde** [comment]
How do I test it?

I'd assume by compiling from source. I just tried to download Visual Studio 2019 Community with the 1903 SDK and am installing it as I write this text. It appears the DDK is now named WDK. Will that combo work?

If not, where how do I get hold of VS 2015 and the (old) DDK?

**Comment by maharmstone** [comment]
Don't bother, they have nothing to do with it!

@MegaZeroX10, please refrain from commenting unless you have something constructive to add.

@mgdde - this must be something weird to do with USB. Are you able to reproduce and send me a minidump?

**Comment by mgdde** [comment]
I guess I could reproduce it though it might take some time (read: over night).
How would I create a minidump?
That last times this occured the system appeared basically dead and required a power off. Or are there some hidden keyboard combos that do the magic?

**Comment by mgdde** [comment]
closed by accident, sry

**Comment by maharmstone** [comment]
It's one of the system options - there's instructions at https://mywindowshub.com/how-to-configure-windows-10-to-create-dump-files-on-bsod/.

Thanks

**Comment by mgdde** [comment]
I'll give it a try tonight. FWIW it stood on "Memory dump" (the normally sized version) and I could not find any on my system. Hopefully the small dump will be created which is in line with the 0% marker on BSOD never changing.

**Comment by mgdde** [comment]
Been trying to provoke another BSOD for 2 days now but for the time being everything works fine. I'm through analysing my music collection twice when previously it did not go through the complete collection once. Seems I can't create the crash at will. I'll keep trying but it might take some time.

**Comment by MegaZeroX10** [comment]
Have you been able to replicate it? If not, this issue should be closed.

**Comment by mgdde** [comment]
Since v1.5 I have not been able to reproduce the problem. I’m fine with it being closed. Should it return I’m happy to reopen it.

Kind regards,
Michael 

Mobil gesendet

**Comment by Fantu** [comment]
I had same issue during a copy on btrfs filesystem.
Winbtrfs 1.7.3 on windows 10 pro 1909 64 bit.

==================================================
Dump File         : 080220-9390-01.dmp
Crash Time        : 02/08/2020 20:23:01
Bug Check String  : NO_MORE_IRP_STACK_LOCATIONS
Bug Check Code    : 0x00000035
Parameter 1       : ffff8388`0571da30
Parameter 2       : 00000000`00000000
Parameter 3       : 00000000`00000000
Parameter 4       : 00000000`00000000
Caused By Driver  : btrfs.sys
Caused By Address : btrfs.sys+76f09
File Description  : WinBtrfs
Product Name      : WinBtrfs
Company           : 
File Version      : 1.7.3
Processor         : x64
Crash Address     : ntoskrnl.exe+1c23c0
Stack Address 1   : 
Stack Address 2   : 
Stack Address 3   : 
Computer Name     : 
Full Path         : C:\WINDOWS\Minidump\080220-9390-01.dmp
Processors Count  : 8
Major Version     : 15
Minor Version     : 18362
Dump File Size    : 414.900
Dump File Time    : 02/08/2020 20:24:37
==================================================

I you need the dump file tell me and I'll post it.
