### ISSUE TITLE
'Btrfs' tab is missing on Windows XP

### ISSUE THREAD

**Issue by SergeGautherie** [maharmstone/btrfs#191]
On Windows XP:
`shellbtrfs.dll` 'Btrfs' tab is not showing up on Btrfs drive properties.

NB:
Drive is working fine otherwise.

**Comment by SergeGautherie** [comment]
Mark emailed me:

> I'm planning to add XP support in v1.5 - I think the only functions missing are RtlSetGroupSecurityDescriptor and RtlAbsoluteToSelfRelativeSD, so it shouldn't be much of an issue.

Looking forward to it :-)

**Comment by maharmstone** [comment]
It turns out the driver _does_ work in XP - the two functions are present in the kernel but presumably undocumented, and Microsoft's header files erroneously restrict their use to WS2003 and onwards.

The only missing functions in shellbtrfs.dll are FindFirstStreamW and FindNextStreamW - I'll need to rewrite it to use NtQueryInformationFile instead.

**Comment by SergeGautherie** [comment]
> present in the kernel but presumably undocumented

Yeah:
'Minimum supported client | This routine is available on Microsoft Windows Server 2003 SP1 and later.'
:-|

--

For what it's worth, with regard to your comment on issue 202, I noticed:
[IOCTL_ATA_PASS_THROUGH IOCTL](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ni-ntddscsi-ioctl_ata_pass_through?redirectedfrom=MSDN):
'Minimum supported client | Available starting with Windows Server 2003.'

Similar case?

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/7539eef804677be3eaea679e4187c8dfbd719f23.

**Comment by SergeGautherie** [comment]
> Fixed by 7539eef.

Confirmed :-)
