### ISSUE TITLE
Multiple undeletable folders with same name

### ISSUE THREAD

**Issue by MakiseKurisu** [maharmstone/btrfs#267]
Currently running 1.7.3, I have multiple folders like this in my Steam folder, which cannot be fixed by scrubbing:
![image](https://user-images.githubusercontent.com/2321672/83597949-20777600-a52e-11ea-92e7-b1bb1d2c678e.png)

When trying to delete them in File Explorer, the error code is 0x80004005:
![image](https://user-images.githubusercontent.com/2321672/83598042-5c124000-a52e-11ea-8cdb-1df6136558cf.png)

I have tried to delete them under Manjaro in Xfce's file explorer, which seems to work (not showing in the window), but under Terminal with ls command the folders are still here.

My partition have entered read-only mode several times, which is likely caused by launching Steam as reported by other users. So this might be related. However I only found out those folders when I performed my weekly backup and it failed due to folders with the same name, so I cannot say this is 100% caused by that issue.

**Comment by MakiseKurisu** [comment]
I'm running Linux scrub overnight to see if that helps. I used WinBtrfs scrub first so I can keep using my computer.

**Comment by maharmstone** [comment]
That's not what scrub's for - what does `btrfs check` say?

I don't remember anybody else reporting problems with Steam, at least not for a couple of years now. I'm not sure what issues you're referring to.

**Comment by MakiseKurisu** [comment]
I was talking about #68, and someone just commented there a month ago. I'll try btrfs check tonight, the scrub under Linux is much slower than WinBtrfs, not sure why.

**Comment by maharmstone** [comment]
Thanks. I can't actually remember if `btrfs check` reports duplicate filenames as an error - IIRC last time I checked it didn't, though definitely should have.

What RAID profile are you using for your metadata - also RAID6 or something else?

Also, the UGC files are apparently what's downloaded from Steam Workshop. Do you know which specific mod this relates to, and which game?

**Comment by ale5000-git** [comment]
Looking at the screenshot there is a backslash in the folder name.
Is it even possible?

**Comment by MakiseKurisu** [comment]
@maharmstone RAID1C4 for metadata, and frankly I don't use Steam Workshop, so I don't know why it was there in the first place.
@ale5000-git shouldn't be possible in normal case but then you shouldn't have folders with same name either. After all system just shows what the filesystem reports, so if filesystem supports it (even though in this case a bug) system will not question it, for example file name "con" is prohibited under Windows, but I think if you create one in Linux you should be able to see it in Windows.

**Comment by MakiseKurisu** [comment]
Here are the output from `btrfs check -p --readonly` and `btrfs check -p --repair`. Unfortunately it doesn't seem to be able to fix the issue. Should I format the partition and restore from backup?
[check_before_repair.txt](https://github.com/maharmstone/btrfs/files/4727614/check_before_repair.txt)
[repair.txt](https://github.com/maharmstone/btrfs/files/4727616/repair.txt)
[check_after_repair.txt](https://github.com/maharmstone/btrfs/files/4727615/check_after_repair.txt)

**Comment by ale5000-git** [comment]
It isn't completely correct because it isn't supposed to handle \ because it is a separator and it is highly possible that the deletion function not handle it correctly and so it isn't able to delete it.
Just my supposition.

For example if you do `cd c:\users\\` the double `\\` is automatically handles as a single `\`.

**Comment by maharmstone** [comment]
Thanks @MakiseKurisu. Backslash is a legal character in filenames on Linux, so I'd try doing `rmdir` on Linux before you reformat. I think you'll probably have to run it once for each duplicate directory, `rmdir *` won't work.

It looks to me like there's three bugs here:
* Steam is trying to create a directory with an invalid character, and we're letting it
* We're allowing duplicate directories to be created (presumably the above is failing, but not being cleaned up properly)
* (From the `btrfs check` log) Some sort of hashing issue involving very long Japanese filenames

**Comment by ale5000-git** [comment]
Command prompt gladly accept this (and it even works):
`cd c:\\\\\\\\\\\\\\windows\\\\\\\\\\\\\\\\\\system32\\\\\\\\\\\\\\\`

So it is possible that a similar things happen in some APIs (but I'm not sure); so it may even be possible that Steam use the backslash in a valid but still strange way.

**Comment by MakiseKurisu** [comment]
Steam could also use forward slash or back slash normally, but we didn't properly handle the translation (I assume we use forward slash internally), something like [this bug in RDP](https://research.checkpoint.com/2019/reverse-rdp-attack-code-execution-on-rdp-clients/).
I'll try `rmdir` and see if that helps.
Those Japanese folders are my music rip and should have nothing to do with Steam. They are in different folders. Do I need to do anything for those errors?

**Comment by nikp123** [comment]
I'd like to add to this issue, but I had different "side-effects". The version is up to date, the partition was created yesterday (as a sort-of large shared drive between OS-es)
This driver still lacks proper safety (in case for example of BSOD or power-loss).

I was copying around 3GB file and it finished (from linux to windows using networking - this is important because these files were reported later as zstd compressed even though I disabled compression - maybe it's that), but soon after windows decided to pull a "deadly update" which is essentially a broken driver shipped by MS that instantly BSODs my machine.

So I didn't want to risk it and booted into linux to check if there were any faults. Oh boy...
When I tried to mount I got a faulty superblock error. 

Perhaps WinBtrfs didn't manage to flush the superblock to the drive in time, oh well... Let me try ``btrfs rescue super-recover``. 

It reports no faults. 

Strange, after that I do a ``btrfs check``. Reports ``parent transid verify failed on 245415936 wanted 843 found 846``, ``bad block 245415936``, ``ERROR: errors found in extent allocation tree or chunk allocation``, ``cache and super generation don't match, space cache will be invalidated`` and the most concerning ``root 5 root dir 256 not found``.

I try clearing the log, nothing.
I try mounting with ``recovery,nospace_cache,clear_cache``.
I try checking data integrity, can't do it since the root dir is broken.

I try the above again, while specifying different superblocks and root dirs (thankfully btrfs decided to make two copies of both), still same result as with ``btrfs check``.

I had no option so I decided ``btrfs check --repair``. Nope, nothing changed. If anything, it just made it even worse.

As I was losing hope, I tried rebooting, different linux kernels and systems. Nope, nothing at all worked.

By now I thought my shit was gone for good. Boot the same Windows 10 for shits and giggles. It mounts it? What, how?

I see that Windows thinks that the drive is empty (180KB out of 480GB or something like that). I open it, everything is inside, still intact (apart from the file from which it had a BSOD). Then afterwards I open the Btrfs properties tab, it reports 80GB used (which it was before the BSOD), but then I think I noticed the error: The metadata was wiped clean 0B out of something 128MB (not sure exactly).

This gives me two ideas:
1) Maybe that broken block (drive error) corrupted the entire metadata tree
2) Windows BSOD-ed right when this driver was updating the metadata tree

Anyways I hope some of this was even remotely useful for possibly fixing issues.
I'd like to see this project progress further, but such a shame it has to deal with these stability issues.

**Comment by nikp123** [comment]
Also forgot to mention that scrub instantly fails on windows, that didn't work either.

**Comment by maharmstone** [comment]
@nikp123 - this is a completely different issue, but I'm fairly certain that it's not an issue with winbtrfs. It's more than likely a hardware problem, which I imagine was also the cause of your BSOD. If I were you, I'd run gsmartcontrol and do an extended self-test.

This is what happens during a metadata flush:
* The driver assigns new addresses for any changed trees, and writes into the free space. If anything goes wrong, we drop into readonly mode.
* We send an ATA flush message, to tell the disk to flush its cache
* We write the superblocks, which point to the new tree addresses

Btrfs is atomic by design - it's impossible for an interrupted flush to leave the FS in a corrupted state.

> Maybe that broken block (drive error) corrupted the entire metadata tree

That's what I think. It could be a bad block, it could be a misdirected write, it could be that the drive said it had written something when it didn't. One of the weaknesses of Btrfs is that it is very vulnerable to HW errors - really it needs a "bad blocks tree" or somesuch.

> these files were reported later as zstd compressed even though I disabled compression

I can't remember the exact logic, but I think that it's the case that if the compress flag is set on a directory, it will still try to compress any new files written there.

> By now I thought my shit was gone for good. Boot the same Windows 10 for shits and giggles. It mounts it? What, how?

This is more that the Linux driver wusses out if there's anything even slightly wrong, whereas the Windows driver gives it its best shot.

**Comment by nikp123** [comment]
@maharmstone 
![image](https://user-images.githubusercontent.com/4696350/87220015-c35ab580-c360-11ea-9f42-48ba62103e2a.png)
you said it

**Comment by nikp123** [comment]
Looking further I have a couple of drive errors, because it seems that some sectors died (around 5) and have been relocated as such. Is ext4 better for this drive (as it does support block relocation) or should I just try to avoid putting anything important on this drive?
Also 6.7k hours and 4.4k power cycles, ooof.

**Comment by MakiseKurisu** [comment]
My backup failed this morning so I went to check my logs. I'm having the same issue again with 1.7.4.

**Comment by maharmstone** [comment]
Fixed by https://github.com/maharmstone/btrfs/commit/b7f8d9325488001ccd7143de495c8d7ce2487703.
