### ISSUE TITLE
Installing results in a "The data is invalid" error

### ISSUE THREAD

**Issue by LegoLivesMatter** [maharmstone/btrfs#281]
Currently running Windows 10 Pro build 20161, and trying to install WinBtrfs by right clicking `btrfs.inf` and clicking `Install` results in a `The data is invalid` error. When I try installing it from the Device Manager, I get a Code 31 error.

EDIT: Rebooting after installing fixed the issue and the driver was working.

**Comment by RepOfCATV95** [comment]
![BTRFS_FAIL00](https://user-images.githubusercontent.com/28668260/87244145-d0dc7200-c42a-11ea-9870-55085e56a5c4.PNG)

**Comment by LegoLivesMatter** [comment]
@RepOfCATV95 That's the exact error that I have, yes.

**Comment by pspslimboy** [comment]
I'm also running into this issue on an older build of Windows 10 (Build 19042.388).

**Comment by Erisa** [comment]
Has anyone with this error tried restarting their computer? I'm running 20175 and got the same thing yesterday.  
After powering off my computer (w/ Fast Startup) and turning it on today it told me that I "need to restart" to "finish installing" the Btrfs controller. So I restarted at that point and the Btrfs driver now works fine.

**Comment by pspslimboy** [comment]
@Erisa 
> So I restarted at that point and the Btrfs driver now works fine.

I found this out about a day ago and forgot to post an update here. I get the scary "The data is invalid" dialog box on 2004+ (I don't get any reboot notification). However, by simply rebooting, the driver works perfectly anyway. Who would've thought? Haha

If this works for the others as well, I guess this is a non-issue, albeit a bit worrisome of an error.

**Comment by Erisa** [comment]
Yeah I think the reboot notification came from powering off with fast startup and then powering back on again. Since it's not a "full" reboot. Glad to see it's solved with a simple reboot, though would be interesting to know why it happens like that in the first place.

**Comment by maharmstone** [comment]
> would be interesting to know why it happens like that in the first place

Same here! It _used_ to work without a reboot, but IIRC Microsoft changed something or other in 1909 which stopped this.

**Comment by Erisa** [comment]
Why was this closed? Even if its worked around with a reboot it's still an issue (Albeit one created by Microsoft) that someone may want to investigate or address at some point in the future.

**Comment by LegoLivesMatter** [comment]
When updating to the latest version, I didn't get an error, but just a prompt to restart the computer. I will reopen the issue if deemed necessary though.

**Comment by claudiusraphaelpaeth** [comment]
The "Data is invalid"-error showed up on 3 fresh setups - Windows 10 Pro | Pro Education | Education

Version	20H2
Installed on	‎9/‎22/‎2020
OS build	19042.487
Experience	Windows Feature Experience Pack 120.2212.31.0

On Education (Enterprise) i have had to disable Fast-Boot - install WinBtrfs - reboot - re-enable Fast-Boot.
Difference on this install was the enabled WSL 2 and revert of Update "September 8, 2020—KB4571756 (OS Build 19041.508)", which was necessary to apply the WSL 2 Kernel Update. Besides this all 3 installs were identical.

**Comment by maharmstone** [comment]
@claudiusraphaelpaeth - you're probably best off commenting at https://github.com/maharmstone/btrfs/issues/296, it's the open version of the same (or similar) issue.

You're using a preview version of Windows, and I've seen it before that the driver has refused to work in such an environment (presumably because Microsoft are still messing around, and don't really expect people to be writing FS drivers). It works for me on 2004.

**Comment by claudiusraphaelpaeth** [comment]
Preview? It is the actual Stable-Channel Release, formerly Semi-Annual. Preview would be the Beta-Channel in the updated Channel-Definitions.

Generally i just wanted to inform that the problem still - meaning in the Stable Channel - exists, as it does as well in LTS-Channel (Windows Server 2019 and Enterprise LTSC 2019).

I had a look into similar issues - wouldn't it be helpful to merge the diverse issues that revolve around the same "problem" (which isn't actually one - since the workaround is simple) and if doable go the safe way of a forced reboot? Because even a forced reboot would still allow for immediate use of btrfs on systems that would allow anyway without reboot.

**Comment by maharmstone** [comment]
Eh? 19042 is the version due out next month, hence "20H2" (second half of 2020). The most recent stable version is 19041, a.k.a. 2004 a.k.a 20H1.

So the problem's solved by doing a reboot? The INF file is _supposed_ to force a reboot - it seems to always do it if you're upgrading, but is touch-and-go when you're installing it for the first time.

**Comment by claudiusraphaelpaeth** [comment]
Ah, now i get it ...

The mentioned installs are indeed the Stable-Release, the Version-jump that makes you assume i am on Preview is due to the KBs that are force-pushed when enabling WSL 2 - or to be precise the Virtual Machine-Feature which basically enabels the Hyper-V Kernel extension which had massive hickups which needed high-priority security patches, which were assigned critical not even a week ago, etc. etc. etc. ... In short: Yes, Microsoft. I use Windows. lol

Regarding the problem:
Yes, it is in all cases - Windows Server/Enterprise LTSC 2019 | Server 2019 SAC/Stable | Windows 10 Pro/Pro Education 20H1 | Server/Windows 10 Pro/Pro Education Beta -  resolved by a  reboot. There is no notification that a reboot is necessary, but instead the mentioned alert.

The problem is not existent in Windows 10 before 20H1, as well as also not on Windows Server 2016/Enterprise LTSB.
