### ISSUE TITLE
Problematic check while mouning a volume on ReactOS

### ISSUE THREAD

**Issue by Extravert-ir** [maharmstone/btrfs#294]
Hello!

I'm working on a brand new storage stack for ReactOS (which is going to be PnP-aware and based on opensourced storage class drivers from Microsoft)

While working on it, I've been hit by a strange check in `check_mount_device` function: https://github.com/maharmstone/btrfs/blob/db269ee1064bd35cd2b73e7b5c349b9ba5f600dc/src/btrfs.c#L4266-L4272
It checks for a device interface name to be empty.
But why, what's the problem for a device object to have a name? Which PDO do you expect to see here?

**Comment by maharmstone** [comment]
Hi Victor,

Yes, I read about that - good luck, I hope it goes well.

This is part of a hack to get Veracrypt to work.

The normal course of action is that the code in `search.c` identifies any Btrfs-formatted block devices via PNP, creates a device `\Device\Btrfs{...}` for any volumes it finds, and then `mount_vol` ignores anything other than the device we've created ourselves. This is so that RAID works properly, as a Btrfs filesystem can span multiple devices.

But for block devices that don't support PNP, the only way we know about them is when Windows tries to mount them. If `mount_vol` calls `check_mount_device` and `no_pnp` gets set to true, it will still go ahead, knowing that it won't be picked up otherwise. The downside of this method is that it doesn't work with RAID.

The proper solution would have been to change Veracrypt so it works with PNP - they also have to do a lot of messing around with mountmgr as a result, when with PNP it should pick up the device automatically.

Does that all make sense?

Mark
