### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by ArKay74** [maharmstone/btrfs#33]
How do I uninstall the driver? It gives me bluescreens and I can't find any uninstall information.

**Comment by maharmstone** [comment]
If you can boot, right-click on the INF file and click Uninstall. If you can't boot normally, I think you will be able to get in via safe mode and delete btrfs.sys.

I'd appreciate it if you could send me a crash dump, so I can find out exactly why it's blue-screening for you.

**Comment by ArKay74** [comment]
I didn't see an Uninstall in the context menu, there was only Install.

Will have to check if I can find the dump.

**Comment by kathiedart** [comment]
There's an uninstall section in the INF file so I think it would be a shell problem if that didn't exist...

**Comment by kathiedart** [comment]
I get the same though, where would the dump be stored?

**Comment by DarthBubi** [comment]
Had the same problem during the feature upgrade to 1703. Ended up deleting it manually from my Linux. It's not the most convenient way, so I looked into this. Apparently there is no Uninstall button in the Explorer shell according to this [Using an INF File to Uninstall a File System Filter Driver](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/using-an-inf-file-to-uninstall-a-file-system-filter-driver):

> There is no "right-click uninstall" option.

But you can use this command from an admin shell to delete the driver according to the DefaultUninstall section:
`RUNDLL32.EXE SETUPAPI.DLL,InstallHinfSection DefaultUninstall 132 path-to-uninstall-dir\btrfs.inf`

Maybe this can be included in the readme for anyone who has a problem with the installed driver?

**Comment by vheathen** [comment]
I also wasn't able to uninstall neither with 'right click uninstall' nor command prompt options. Was forced to remove with another OS boot and manual deleting btrfs.sys. By the way, it's not possible to remove the driver from btrfs's 'Unknown device' properties in the Device manager as well.

**Comment by mariolpantunes** [comment]
I have the same issue as @vheathen. An 'Unknown device' is always appearing in the Device Manager.

**Comment by NinoM4ster** [comment]
This thing messed up with my system... I can't install (or even uninstall) the software anymore. I tried everything, even deleting the .SYS file under `...\System32\drivers`. (yes, I am using the latest version, 1.1)

I had installed it previously, but I disabled it (without removing it. I don't remember how though) because I needed a VM to have access to a physical btrfs disk, but it couldn't because the btrfs driver mounts it automatically.

Anyway, I couldn't get it working after a successful install (the drives didn't showed up, and I couldn't find anything under Storage Volumes, at Dev. Mgr.), then I removed the .SYS file and deleted the `btrfs` "folder" on _regedit_. I think that's what messed everything up. but it doesn't make sense, because before installing the driver, there's no btrfs stuff on _regedit_, so why deleting it breaks things?

Also, I noticed that it was supposed to copy some DDL files on `...\System32\drivers` (I tried installing an older version and it was trying to replace some files), but I couldn't find these files on the destination folder.

**Comment by b-f-** [comment]
I have the same issue as @vheathen. An 'Unknown device' is always appearing in the Device Manager.
After I reinstall the driver (success), I get the "device is not functioning properly".

![image](https://user-images.githubusercontent.com/2358754/73125581-9aa85480-3fa8-11ea-852f-fe960b5e745c.png)

**Comment by maharmstone** [comment]
Closing old issues
