### ISSUE TITLE
[Question] Why is btrfs.sys a device driver?

### ISSUE THREAD

**Issue by TheMadHau5** [maharmstone/btrfs#335]
The title is my question: why is `btrfs.sys` a device driver, instead of being a filesystem driver like `fastfat.sys`, `ntfs.sys`, `refs.sys` and the rest? Is there any architectural reason (like convenience in coding), or is it just how you did it?

**Comment by maharmstone** [comment]
I've no idea what you're going on about - it's a filesystem driver by definition, being a driver that implements a filesystem. It's the exact same sort of thing as `ntfs.sys`.

**Comment by TheMadHau5** [comment]
I mean its identification; in its service file, it appears to not be a filesystem driver, but a regular device driver. This can also be confirmed in Process Hacker. I was just asking why this is the case, and if it is possible (and easy) to "group" it with the others.

**Comment by ticpu** [comment]
The only guess I have right now is that Btrfs's `Group` key in the service declaration has `File System` as value instead of `Boot File System`.

Every other file system services declared in `HKLM\SYSTEM\ControlSet001\Services\` have the later, such as:
- cdfs
- udfs
- ntfs
- exfat
- fastfat
- ReFS

Is that what you meant?  Those that show as `File System` only are Btrfs and other weird FS that don't really exist such as Msfs or CimFS.

**Comment by TheMadHau5** [comment]
It could be that, yeah. There's a `Type` key there too (set to 1 for btrfs, and 2 for all the others, including the weird ones). Manually trying to set `Type` does nothing, and changing btrfs' group to `Boot File System` for some reason causes the driver to not work.
