### ISSUE TITLE
Explorer file compression status

### ISSUE THREAD

**Issue by BlueAmulet** [maharmstone/btrfs#340]
It seems like the driver currently does nothing with the FILE_ATTRIBUTE_COMPRESSED attribute, including not letting you modify it at all. I copied some NTFS compressed files into a Btrfs drive, the compression status stayed and I can't figure out how to unmark the files as being compressed so I guess those files are forever blue now.

It would be cool if files with compressed extents could be reported to Windows as compressed, and files with no compressed extents also being reported uncompressed.

It would also be possible to use the attribute to indicate the file's compression setting, but that might get confusing if a user changes the compression setting of a file and the file is now/no longer indicated as blue, but the actual contents haven't been compressed/uncompressed at all.

**Comment by maharmstone** [comment]
> I guess those files are forever blue now

What does `compact /U` do? If it doesn't let you clear it, maybe I need to make it so that FILE_ATTRIBUTE_COMPRESSED gets cleared silently on creation.

It's deliberate that FILE_ATTRIBUTE_COMPRESSED isn't mapped to the Btrfs compression - Windows seems to assume that compressed files can be fed successfully to RtlDecompressBuffer. I'm fairly sure that even though the "Compact OS" files on Windows 10 are compressed, they don't have FILE_ATTRIBUTE_COMPRESSED set.

**Comment by BlueAmulet** [comment]
Oh, compact /U doesn't do anything to the files, it'll say several files were uncompressed but they remain blue and rerunning the command will just say the files are uncompressed again. I haven't noticed any issues with the files though, it was a compressed game and the game still runs fine and the files validate.

**Comment by maharmstone** [comment]
Closing old issues
