### ISSUE TITLE
How do you mount partitions?

### ISSUE THREAD

**Issue by alucryd** [maharmstone/btrfs#347]
Hi there,

I can't find any documentation on how to mount a BTRFS partition. I have a BTRFS formatted linux partition alongside my NTFS formatted windows partition, but it doesn't show up after installing winbtrfs and rebooting. I'm not using MD, it's a plain partition, I can see it in the windows disk manager but can't assign a drive letter to it.

Is mounting supposed to be automatic? Is there a way to force it?

Thanks in advance.

**Comment by maharmstone** [comment]
Short answer is you don't - Windows mounts all volumes automatically.

Things to check:
* Is the `btrfs` service running? Try `sc query btrfs`. If it's not, what happens when you run `sc start btrfs`?
* In Device Manager, there should be an entry under "Storage controllers" called "Btrfs controller". It should have one or more entries called "Btrfs volume" underneath that.
*

**Comment by alucryd** [comment]
Thanks for the quick answer, turns out scoop doesn't fully install the driver, it did prompt UAC and ask me to trust it, but that's it. Following your instructions worked and the partition popped right up. Thanks!
