### ISSUE TITLE
How am I supposed to mount a degraded array? (1 device missing)

### ISSUE THREAD

**Issue by cooper2k4** [maharmstone/btrfs#355]
Thank you for creating WinBtrfs! This seems to be the perfect filesystem for dual Windows/Linux usage.

The featurelist states the support of degraded mounts but I can't find out how to do it 😢 

I have three devices as RAID1 (`-dconvert=raid1 -mconvert=raid1`) and tried to mount it under Windows with one device missing. There appears just one inaccessible drive in Explorer and I cannot access the Btrfs-Menu. In Linux it works with `mount -o ro,degraded /dev/sda3 /mnt/drive`.

What is the equivalent for Winbtrfs? Can you add this to the FAQ?

**Comment by kf6kjg** [comment]
Looks like it's not specified in the README, but [according to the code](https://github.com/maharmstone/btrfs/blob/3641f5742c862e6dd8c7db3fe81f25af7a470346/src/registry.c#L812), committed May 20, 2017, there's a flag you can set in the registry named "AllowDegraded". Looks like it's a DWORD value with a default of 0.

*Caveat emptor*: I'm a nobody relative to this project, I just installed it myself a couple of hours ago so that I could use my backup OS, Windoze, to keep working until the weekend when I can concentrate on fixing my Linux install. So I can't tell you if this option is good, bad, ugly, or some combination of them.

**Comment by maharmstone** [comment]
Whoops, you're right. No wonder @cooper2k4 was having issues.

I've added it to the README.md now - sorry!

**Comment by cooper2k4** [comment]
Thank you Mark :+1:

If using `AllowDegraded` in combination with `Readonly` it should be save, or?

**Comment by maharmstone** [comment]
@cooper2k4 - yes, that's right
