### ISSUE TITLE
Installation failed on Windows 10

### ISSUE THREAD

**Issue by Grigoriy0** [maharmstone/btrfs#397]
**OS version**: Windows 10 Pro 1903
**btrfs version**: 1.7.8.1

I tried install via PowerShell (with Administrator privilegies also) 
`RUNDLL32.EXE SETUPAPI.DLL,InstallHinfSection DefaultInstall 132 btrfs.inf`
But I always get error message "Установка не выполнена" ("Installation failed")

And I even don't know how to get more detailed information about this error.

**Comment by colin-williams** [comment]
I am facing a similar issue. I set the registry as mentioned in the documentation https://github.com/maharmstone/btrfs#secureboot . 

Note that I also set the following registry setting because the install option was missing from the file explorer . https://answers.microsoft.com/en-us/windows/forum/all/install-option-missing-from-the-context-menu-of/23524ad3-1687-4c2d-ba26-b249b4c4d8e9

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎10/‎10/‎2022
OS build	19044.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0

Now after setting the above and getting the install option I get:

"This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

Then trying the Powershell option similar to @Grigoriy0 I get "Installation failed".

I am trying this on a MS Surface 2 laptop for which I have Administrator Access to mount / access btrfs filesystems on an external hard drive

**Comment by colin-williams** [comment]
It looks like I made forward progress. Using  `rundll32 syssetup,SetupInfObjectInstallAction DefaultInstall 128 .\btrfs.inf` and I was able to install. A notification popped up after install but disappeared quickly and I cannot view. I am going to try a reboot and see if I can access the btrfs filesystems.

**Comment by colin-williams** [comment]
> > I am trying this on a MS Surface 2 laptop
> 
> Just to be clear, this is an ARM laptop, right?

No, from System Information

Processor	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz, 1896 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by sskras** [comment]
It seems the issue is pretty valid. But the interested folks will ping for reopening anyways, I guess. :)
