### ISSUE TITLE
Cannot access folder while copying files to that folder

### ISSUE THREAD

**Issue by voltagex** [maharmstone/btrfs#406]
![image](https://user-images.githubusercontent.com/83080728/129471789-8a71153a-6d9f-4be4-b307-a85644575e23.png)

![image](https://user-images.githubusercontent.com/83080728/129471840-35162357-d9e6-4ba9-9045-854abb340104.png)

```
Location is not available
E:\root\data is not accessible
The process cannot access the file because it is being used by another process.
```

E: is a btrfs filesystem created by the Fedora 34 installer.

I'll come back to this when I'm not copying large amounts of data to install the debug drivers and see if I can see anything there - thought it was still worth reporting this issue.

```
Microsoft Windows [Version 10.0.19043.1165] 21H1
DriverVer   = 06/13/2021,1.7.8.1
```

**Comment by jarrarte** [comment]
I have a similar problem using v1.8.1 on Win10. 

I'm using Synology's Cloud Station Drive (an application to synchronize NAS shares and local directories). When I'm changing files and the sync job kicks in (second(s) after modifying files), it usually makes the directory unavailable in File Explorer or synchronization fails throwing a permissions error.

It also happens when developing Java code. When building the project, I usually get this error in IntelliJ:

```
Internal error (java.io.IOException): The process cannot access the file because it is being used by another process
java.io.IOException: The process cannot access the file because it is being used by another process
	at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:417)
	at java.base/java.io.File.getCanonicalPath(File.java:626)
....
```
