### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by mrtechsantiago** [maharmstone/btrfs#410]
Hi, good morning

First of all, thank you for all your awesome job that give us the ability to use the wonderfull btrfs file system on windows.
Now, I dont know if this is a task is in progress but the winbtrfs driver works very well installed on windows 10 but now I updated to windows 11 and is not working. It halts windows "freezing" the GUI.

Are any task running to make this awesome driver works on Windows 11? Thanks

**Comment by Masamune3210** [comment]
A reminder that Windows 11 is still in Dev Preview, so a lot of things can and will be broken

**Comment by maharmstone** [comment]
^ This. I'm waiting until Windows 11 is released (October?) before doing anything with it. There's a good chance the problem will sort itself.

**Comment by OlegVF** [comment]
Попробуйте исходный код самостоятельно откомпилировать в Visual Studio 2019 используя при этом [11wdksetup.exe](url=https://go.microsoft.com/fwlink/?linkid=2166289) и [22000.1.210604-1628.co_release_WindowsSDK.iso](url=https://go.microsoft.com/fwlink/?linkid=2166460)

**Comment by OlegVF** [comment]
- Если Вы в Windows ранее отключали авто назначение букв разделу, то выполните:
```diskpart```
```automount enable```
```exit```
или
```REG ADD HKLM\SYSTEM\CurrentControlSet\Services\MountMgr /v NoAutoMount /t REG_DWORD /d 0```
В случае с BtrFS при форматировании раздела это необходимо, чтобы потом не ломать себе голову над вопросом, почему в проводнике не появился отформатированный раздел.

- Включение Сжатие данных:
```REG ADD HKLM\SYSTEM\CurrentControlSet\services\btrfs /v Compress /t REG_DWORD /d 1```

- Форматирование раздела в BtrFS должно выполняться под Администратором:
```mkbtrfs /csum:crc32c \Device\Harddisk№\Partition№```
Где под № подразумевается номер диска и раздела, который будет отформатирован в BtrFS.
Возможные значения параметра csum: crc32c, xxhash, [sha256](https://github.com/amosnier/sha-2) и [blake2](https://github.com/BLAKE2/BLAKE2).

- Если раздел не форматируется в BtrFS, скорее всего в этом виновна Сторонняя служба или программа, блокирующая доступ к диску. Например: **Acronis Active Protection Service** - Попробуйте отключить ее.

- После форматирования раздела в BtrFS рекомендуется сделать следующие действия в **diskpart**:
```list disk```
```select disk №```
```list partition```
```select partition №```
Если MBR, то: 
```set id FD```
или 
```set id 83```
Если GPT, то: 
```set id A19D880F-05FC-4D3B-A006-743F0F84911E```
или 
```set id 0FC63DAF-8483-4772-8E79-3D69D8477DE4```
Если GPT и хотите в диспетчере дисков заблокировать раздел от удаления, то выполните команду: 
```GPT ATTRIBUTES=0x0000000000000001```
Где под № подразумевается номер диска и раздела, который был отформатирован в BtrFS
Делается это для того, чтобы Windows в диспетчере дисков корректно реагировало на наличие раздела с BtrFS и не предлагала его отформатировать и не пыталась самовольно назначить ему букву, так как драйвер BtrFS сам назначит данному разделу букву, если включено авто монтирование дисков в Windows.

- Букву вручную можно назначить так:
```REG ADD HKLM\SYSTEM\MountedDevices /v \DosDevices\#: /t REG_BINARY /d №```
где # — это желаемая свободная буква, назначаемая диску.
где № — это шестнадцатеричное значение GUID раздела, увидеть и сопоставить его можно по командам:
```REG QUERY HKLM\SYSTEM\CurrentControlSet\services\btrfs /f -``` - Доступные BtrFS разделы по GUID
```REG QUERY HKLM\SYSTEM\MountedDevices /f :``` - Смонтированные разделы по GUID

- Отключение службы BtrFS:
```REG ADD HKLM\SYSTEM\CurrentControlSet\services\btrfs /v Start /t REG_DWORD /d 4```

- Включение службы BtrFS:
```REG ADD HKLM\SYSTEM\CurrentControlSet\services\btrfs /v Start /t REG_DWORD /d 1```

- Если BtrFS устанавливается в Windows 10, то нужно выполнить:
```REG ADD HKLM\SYSTEM\CurrentControlSet\Control\CI\Policy /v UpgradedSystem /t REG_DWORD /d 1```

**Comment by maharmstone** [comment]
@OlegVF, if you wish to comment here, you need to use the same language that everybody else is using.

**Comment by OlegVF** [comment]
переводи на русский, урод...

**Comment by OlegVF** [comment]
дебил, когда научишься уважать окружающих?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/maharmstone/btrfs/issues/410#issuecomment-911052593

Why not merely use http://translate.google.com?

**Comment by maharmstone** [comment]
That's precisely what I said to him.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/maharmstone/btrfs/issues/410#issuecomment-913829727

Usually, allowing somebody to type in their native language is better because it shall allow them to better articulate what they are desiring statement of because //translate.google.com is not perfect at translation, although I have understood why you would rather what you chose, and thus shall not discuss this topic more to preserve the topic of [this thread](http://github.com/maharmstone/btrfs/issues/410).

**Comment by maharmstone** [comment]
Google Translate was going to be involved at some stage of the proceedings regardless, as I don't speak Russian and he apparently doesn't speak English. Oleg was warned elsewhere, and is now blocked for being abusive (I'm an "урод" and "дебил" apparently, which don't appear to be too complimentary).

**Comment by lhorace** [comment]
I'm using it here on Windows 11. The only issue I've observer is on the first reboot, takes forever to show logon screen then the log in process never completes. Subsequent force reboot remedied the problem. AFAICT, the cursory articles that I've come across indicated that there isn't significant changes to Windows core. Although, it would be nice if any work that maybe needed could be work on now, AFAIK, Windows 11 is in the beta channel.

**Comment by Masamune3210** [comment]
Dont believe everything you read in articles, there are more changes in 11 than most people realize, especially behind the scenes. Still better to wait for GM release imo

**Comment by lhorace** [comment]
I disagree, the changes to the Windows kernel doesn't bring significant _breaking_ changes, even from Microsoft themselves. Albeit, MS did say there was a new storage stack. Nevertheless, nothing wrong starting work now, as the release date is around the corner to have something on day one.

**Comment by lss4** [comment]
> Dont believe everything you read in articles, there are more changes in 11 than most people realize, especially behind the scenes. Still better to wait for GM release imo

I agree with this. I think it's better off waiting for the OS to be mature enough.

It was already the case with Win10 that builds closer to release might contain breaking changes that would make existing drivers stop working, not to mention "feature updates" can be considered a way to convey to users that something _"might be broken"_ in the update process.

And you can't be sure that feature updates would not break the WinBtrfs version you're currently on. When 20H1 just came out, a system of mine which runs 19H2 simply couldn't update to 20H1 as the WinBtrfs version I had at that time (installed when I initially installed Win10 on it and haven't updated since) caused the update process to BSOD at the last stage (which caused the update to revert), and only after manually updated to the latest WinBtrfs available at that time did I succeed in updating that system to 20H1.

Honestly, compared to Linux, you're _on your own_ to keep your software up-to-date which can be difficult, since Windows totally lacks a _proper_ package management system for handling every aspect of software installation. Chocolatey mostly acts as a wrapper to acquire the software installer and perform unattended installations, which is still different from how package managers work on Linux and does not always work. If the software developers themselves have logic in their software to check for updates, it might get in the way as Chocolatey won't be informed.

**Comment by Masamune3210** [comment]
Thankfully winget is trying to remedy the package system issue a bit for Windows in a semi-native way, but even then, it still wont be like Linux unfortunately

**Comment by lhorace** [comment]
> Dont believe everything you read in articles, there are more changes in 11 than most people realize, especially behind the scenes. Still better to wait for GM release imo

>> I agree with this. I think it's better off waiting for the OS to be mature enough.

I don't agree completely. I just wanted to point out, I was referring to Windows 11 in the beta channel. In fact, companies are already developing and releasing drivers for this version. And MS has already sent out this version for PC validation. In fact, this is the best time, if the author were to encounter any issues to provider his/her feedback _"since it will help our engineers make sure that key issues are identified and fixed before a major release"._ More precisely, it's closer to `Release Preview` than it is to `Dev Channel`.

**Comment by lss4** [comment]
> > Dont believe everything you read in articles, there are more changes in 11 than most people realize, especially behind the scenes. Still better to wait for GM release imo
> 
> > > I agree with this. I think it's better off waiting for the OS to be mature enough.
> 
> I don't agree completely. I just wanted to point out, I was referring to Windows 11 in the beta channel. In fact, companies are already developing and releasing drivers for this version. And MS has already sent out this version for PC validation. In fact, this is the best time, if the author were to encounter any issues to provider his/her feedback _"since it will help our engineers make sure that key issues are identified and fixed before a major release"_. [1] More precisely, it's closer to `Release Preview` than it is to `Dev Channel`. Otherwise it's likely to lapse due to technical issues.
> 
> 1. https://blogs.windows.com/windows-insider/2020/06/15/introducing-windows-insider-channels/

I think unless there are enough Insiders interested in this driver, it won't be easy for M$ to be quickly informed about any issues related to it (in case it's a bug/regression on M$ side). If you're an active Insider feel free to test this driver a bit more :smile:.

And a warning: You can't be sure the OS (or feature update) is safe when it just hits RTM either (remember the [Win10 1809 incident](https://answers.microsoft.com/en-us/windows/forum/all/windows-10-1809-update-deleted-all-files-from/ff608374-2686-4a08-a4c2-caa4caa6d4e1)). That issue even forced M$ to temporarily retract the update and re-release it after they addressed it.

**Comment by lhorace** [comment]
> I think unless there are enough Insiders interested in this driver, it won't be easy for M$ to be quickly informed about any issues related to it (in case it's a bug/regression on M$ side). If you're an active Insider feel free to test this driver a bit more smile, as it might actually help getting the work started.

I am testing the driver, but I'm not sure my feedback to MS would help move things a long or provide valuable technical information. The best approach would be were if the author ran into issues and wanted votes. I can do that. The only issue thus far is intermittent where sometimes on boot, explorer would hang to list drives. But that could be issue with the disk itself.

> You can't be sure the OS (or feature update) is safe.

I wouldn't be in the Beta channel, yet-to-release WinBTRFS if I were worried about risks. :)

**Comment by maharmstone** [comment]
This is a futile discussion, as I've already made it clear that I'm not doing anything to do with Windows 11 until it's released. Microsoft have made it clear that they disapprove of individuals writing kernel-space code, so they're not going to care much about any feedback.

**Comment by bentrop** [comment]
The Windows 11 code that has already gone out to OEMs is significantly older than what is currently tested in the Beta channel, in two weeks there will be systems on the shelves with far older Windows 11 builds than currently available for testing.
For all intents and purposes, Windows 11 has already gone "RTM" weeks, if not months, ago, Microsoft simply no longer calls it that.

I have been unable to get WinBTRFS working on Windows 11 with secure boot enabled.
Can anyone confirm that the "UpgradedSystem" registry entry is now being ignored by Windows 11?

I assume this would be a near unsurmountable hurdle if true? Especially if Microsoft increases secure boot enforcement in the future.

**Comment by lss4** [comment]
> I have been unable to get WinBTRFS working on Windows 11 with secure boot enabled.
> Can anyone confirm that the "UpgradedSystem" registry entry is now being ignored by Windows 11?
> 
> I assume this would be a near unsurmountable hurdle if true? Especially if Microsoft increases secure boot enforcement in the future.

TPM2.0 (either through physical module or through CPU) is already mandatory, though it can be _unofficially_ disabled (who knows if M$ would eventually patch it upon RTM). Not sure if Secure Boot might end up mandatory too.

> Microsoft have made it clear that they disapprove of individuals writing kernel-space code, so they're not going to care much about any feedback.

"In the name of security", I think. They don't want others to write code operating at that level for fear that vulnerabilities might be introduced, yet who knows how many epic 0days are still at large (like [this one](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-34527) which existed for quite long and was not known until recently)...

**Comment by maharmstone** [comment]
This is part of why I'm so reluctant to touch Windows 11 before release - there's such a strong disconnect between what Microsoft says is compulsory etc., and what actually turns out to be the case.

If there was a situation where Windows insisted on Secure Boot in all circumstances, I think that'd be a pretty good incentive for me to finish off Quibble.

**Comment by bentrop** [comment]
> TPM2.0 (either through physical module or through CPU) is already mandatory, though it can be unofficially disabled

Yes, TPM 2.0 and Secure Boot are two different things. TPM 2.0 officially has to be **enabled**, there's no officially supported way around that.
At least for the first incarnation of Windows 11 (22000.x), the system only has to be Secure Boot _capable_ but Secure Boot can, currently and officially, be **disabled**. Given the capability mandate, it stands to reason that future Windows 11 version may also enforce Secure Boot to be enabled.

For that reason - and because Secure Boot has to be enabled by default on new OEM systems and is otherwise being aggressively pushed by Microsoft - a Secure Boot compatible version of WinBTRFS should be the ultimate goal.

Ironically, the Linux distro whose file system I'm trying to access via WinBTRFS, Fedora 34, is already fully Secure Boot capable with no restrictions or compatibility issues.

**Comment by bentrop** [comment]
> This is part of why I'm so reluctant to touch Windows 11 before release - there's such a strong disconnect between what Microsoft says is compulsory etc., and what actually turns out to be the case.

Microsoft's communication left a lot to be desired, that much is true. But the Beta/effectively RTM version of Windows 11 (22000.x) and the official requirements are mostly in-sync now. The offending requirements are as follows:

TPM 2.0: Has to be present and _enabled_. There is no official support for any system without.
Secure Boot: The system has to be capable of this, but it may be user _disabled_. This is an officially supported system configuration. New OEM systems _have_ to ship with it _enabled_ but may still grant users the option to disable this.

There will be no full Secure Boot mandate upon release of Windows 11, but, yeah, future versions may enforce this stronger.

**Comment by maharmstone** [comment]
> Secure Boot: The system has to be capable of this, but it may be user disabled. This is an officially supported system configuration.

Thank you - this is a relief to know.

> a Secure Boot compatible version of WinBTRFS should be the ultimate goal

Almost certainly not going to happen. I've been told by the certificate authority that they won't issue EV certificates to individuals, only corporations.

**Comment by lhorace** [comment]
> I have been unable to get WinBTRFS working on Windows 11 with secure boot enabled.

@bentrop 

I'm on the latest build, with the registry hack, with Secure Boot and TPM 2.0 enabled. I don't recall what build I was on at the time.

**Comment by maharmstone** [comment]
Fixed on 1.7.9.

**Comment by Squall-Leonhart** [comment]
UpgradedSystem still works on windows 11 22000 and 22621.

**Comment by Oyami-Srk** [comment]
Confirmed UpgradedSystem not works on my laptop with Windows11 22621.382
Atleast nothing works until I disable the secure boot.

**Comment by Squall-Leonhart** [comment]
UpgradedSystem works fine .
