### ISSUE TITLE
How to remove the restriction on 255 bytes in the file name in the BtrFS driver version 1.7.8.1

### ISSUE THREAD

**Issue by OlegVF** [maharmstone/btrfs#415]
You need to change the following lines in the source file btrfs.c in the src folder:

-  You need change a line **1025** in the source code:

       data->MaximumComponentNameLength = 255; // FIXME - check

- change to:

       data->MaximumComponentNameLength = 510; // FIXME - check

-  You need change a line **5788** in the source code:

       if (utf8len > 255)

- change to:

       if (utf8len > 510)

-  You need change a line **5790** in the source code:

       else if (stream && utf8len > 250) // minus five bytes for "user."

- change to:

       else if (stream && utf8len > 500) // minus five bytes for "user."

The reason for these actions is that Windows uses UTF16 encoding for encoding the file name and the file name length is limited to 255 characters, not 255 bytes. Also, Russian characters in UTF8 encoding (BtrFS) are encoded in 2 bytes per character, which leads to a conflict and a 2-fold reduction in the length of the file name. To fix the situation and add support for 255 Russian characters in the file name, we have to increase the limit of 255 bytes by 2 times. The developers mistake is to measure the length of the file name in bytes, not in characters!!!

Please ask the developer of BtrFS for Windows to make these changes to their solution for greater compatibility with Windows...

**Comment by maharmstone** [comment]
This isn't a bug. Filenames on Linux are limited to 255 bytes.

**Comment by ale5000-git** [comment]
@maharmstone
So the changelog is wrong since there is:
`Forced maximum file name to 255 UTF-8 characters, to match Linux driver`
that in case every character is 4 bytes then the filename will be 1.020 bytes long.

PS: It seems like a bug by design (by the linux developers) since for a filename with all characters of 4 bytes the limit will be 63 characters that is quite short.

**Comment by maharmstone** [comment]
It's not wrong - the word "characters" in this context nearly always means "code units" rather than "code points". This is how it's used in e.g. the C specification.

I agree, it sucks that it might only be 63 code points, but them's the breaks...

**Comment by lss4** [comment]
> It's not wrong - the word "characters" in this context nearly always means "code units" rather than "code points". This is how it's used in e.g. the C specification.
> 
> I agree, it sucks that it might only be 63 code points, but them's the breaks...

Hmm... I think a warning should be placed somewhere (like in FAQ) in case a user can't copy a file from a NTFS partition to a Btrfs one due to file name being too long, as technically the maximum file length of NTFS (in bytes) is twice that of Btrfs and this can definitely happen.

And yeah, this ancient limitation really sucks as in some scenarios it's quite possible to end up with a filename more than 255 bytes, breaking workflows unexpectedly.

**Comment by brian6932** [comment]
This is a pretty annoying limit, maybe there should be a registry entry the user can set to change this limit?

**Comment by maharmstone** [comment]
I'm not going to intentionally break compatibility with Linux.

The correct place to discuss this is on one of the Linux kernel mailing lists. If you do, make sure you copy me in.
