### ISSUE TITLE
File/directory permissions changed

### ISSUE THREAD

**Issue by simon50keda** [maharmstone/btrfs#421]
Hi,

I've been using btrfs for shared data usage between windows and linux. However when existing files, which are owned by linux user, get resaved in windows permissions get changed.
When I return to linux resaved file has "nobody" assigned as the owner and rest of it is set to readonly.

Is that how it's supposed to be or should this be considered a bug?

**Comment by maharmstone** [comment]
Have a look at the Mappings section of the README, which tells you how to map your Windows SID to your Linux uid.

If it's resetting the permissions to 644 as well, it's probably because the program is "saving" the file by creating a new one and deleting the old one - I know some versions of Office do this, for instance.
