### ISSUE TITLE
Group mapping and preserving ownership/permissions

### ISSUE THREAD

**Issue by Dawnflash** [maharmstone/btrfs#43]
I noticed that editing (and saving) files with non-elevated privileges erases existing perms and ownership.
It sets the owner group to nobody and user according to the set mapping.
This doesn't happen with privileged editing and as we usually do edits in unprivileged programs like Sublime, it would be great if privileges and ownership data could be preserved.

Could you add a mapping for groups to the registry, too?

**Comment by maharmstone** [comment]
Thanks, I'll have a look at what Sublime is doing. We only change owners when Windows tells us to, so I'm not sure what's going on there. I'll need to check it's not doing the same thing on NTFS.

I'll have a look at group mapping too. It's not terribly useful, as Windows doesn't do an awful lot with groups, but for completeness' sake. At the very least, new files should be inheriting the GID from their parent rather than being set to nobody.

**Comment by maharmstone** [comment]
I've added group mapping with today's patches. It defaults to mapping the Users group to gid 100, which is usually "users" on Linux, though you can add others if you like.

Tried Sublime and it worked fine for me. This was build 3126 of the portable 32-bit version - I edited a file owned by root, and saving it didn't change its uid. Which version of Sublime are you using?

**Comment by Dawnflash** [comment]
Thx for the patch, yes, it's my Sublime that does this, I should have tested with other editors.
It's an older build 3059, I'll just update.
Thanks for the heads up :)
