### ISSUE TITLE
Can't copy some Steam files to

### ISSUE THREAD

**Issue by ponjadito23** [maharmstone/btrfs#436]
I was transferring my games folder to a btrfs volume and it immediately stopped when trying to copy steam.dll.
It shows a message which translated says something like "The specified file name is invalid or is too large. Specify another name".
I tried renaming it and copying to root and still happens the same thing.

![file name invalid](https://user-images.githubusercontent.com/17890647/140650580-510ddedb-a381-4b7e-80d6-4930e9fbf465.png)

I'll attach a zip containing a wim which has the file, I can't upload it as zip directly because the bug goes away
[steam.zip](https://github.com/maharmstone/btrfs/files/7492518/steam.zip)
.

**Comment by ponjadito23** [comment]
I tried copying more files and some other things not related to steam have the same problem too.
I think I made those files when transferring to SAMBA running on a Raspberry Pi with the drive formatted as NTFS

**Comment by maharmstone** [comment]
Thanks for the WIM file, that's very helpful. I see the problem - steam.dll has an alternate data stream called DOSATTRIB, which I have as a reserved name. You might want to raise this with the Samba people as a bug - if it's using NTFS, it ought to be storing the DOS attributes directly, rather than using an xattr as a workaround.

If Explorer's choking on these files, you might have more luck by using the command prompt. Or possibly just use `rsync` on Linux.
