### ISSUE TITLE
Windows on ARM (SQ1) not installing (with and without Secure Boot)

### ISSUE THREAD

**Issue by 7coil** [maharmstone/btrfs#440]
_I'm sorry for being a Windows on Arm user_

## System Specification
- Microsoft Surface Pro X (SQ1)
- Microsoft Windows 11 21H2 (22000.348)
- aarch64

On WOA, the installation of WinBtrfs 1.7.9 with Secure Boot (Microsoft Keys only) and [the registry key trick](https://github.com/maharmstone/btrfs/issues/270#issuecomment-761693403) results in the following error:
> Error 0x800B0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
![image](https://user-images.githubusercontent.com/13886925/143269763-a2810022-8f0b-4bfa-b289-9fa4320550f6.png)

The following occurs with Secure Boot disabled:
![image](https://user-images.githubusercontent.com/13886925/143280167-210378b5-b375-415e-923a-35aa40ddc6bf.png)
![image](https://user-images.githubusercontent.com/13886925/143280390-feec6eeb-a7b8-4094-9638-e748760141a6.png)

The installation appears to succeed, but does not appear, nor does my btrfs formatted drive appear/get mounted.

**Comment by maharmstone** [comment]
> I'm sorry for being a Windows on Arm user

You have my condolences.

My experiments with Windows on ARM have been less than successful - I eventually managed to get it working with Qemu but it took half an hour to boot. Messing around with a Raspberry Pi was likewise unusably slow.

Microsoft clearly have some different rules when it comes to signing on ARM. I found I could get the driver to load when I attached a kernel debugger but not otherwise - I don't know what that's about.

What happens if you run `sc start btrfs` in an admin command prompt - does it give you an error about signing?

**Comment by 7coil** [comment]
![image](https://user-images.githubusercontent.com/13886925/143293346-7fa1612e-5bce-4673-80a5-10bf1c479bf4.png)

Never installed (apparently)

**Comment by maharmstone** [comment]
Closing old issues

**Comment by Git-North** [comment]
I'm having the same problem
