### ISSUE TITLE
Visual Studio 2022 Error compiling 'call to immediate function is not a constant expression'

### ISSUE THREAD

**Issue by iTrooz** [maharmstone/btrfs#498]
Hey !

When I try to build the driver from source, I get the error 'call to immediate function is not a constant expression' (duplicated a ton of times, prob because of the template)

I'm using Visual Studio 2022 with Windows 11 SDK 10.0.22621 (and yes I have installed WDK)

I also reproduced the issue in a github action CI : https://github.com/iTrooz/btrfs/runs/7508970871?check_suite_focus=true

From what I understand, this is because Visual Studio 2022 has become more strict with errors, in a way that Visual Studio 2019 wasn't

I'm trying to fix the issue right now, but it would be nice to hear your thoughts on this

**Comment by iTrooz** [comment]
Fixed it ! I essentially used vformat to avoid constant expressions (see https://github.com/iTrooz/btrfs/commit/c1bc1b65f341151f420a72aa4d44566f7f9aa2a1)

**Comment by maharmstone** [comment]
Thanks @iTrooz. Yes, they appear to have implemented P2216R3 since I wrote the code.

I've incorporated your fixes as https://github.com/maharmstone/btrfs/commit/8368b49f27142c4cad06c3ca24983af10409b7c1, thank you. Annoyingly `std::vformat` appears to be the only way to do it in MSVC - `fmt::format_string` is better, as it does compile-time checking, but it ICEs MSVC...
