### ISSUE TITLE
Does not work on Windows 7 x64

### ISSUE THREAD

**Issue by mailyspamy** [maharmstone/btrfs#560]
Does not work on fresh install of Windows 7 x64
Only version 1.0 connects btrfs drive, but is not possible to open.
It is also needed to disable signed drivers.

**Comment by maharmstone** [comment]
Have you fully updated Windows? IIRC the signature thing at the very least is solved by a Windows Update.

**Comment by rautamiekka** [comment]
Take a look at LegacyUpdate.net, it might have something: https://www.youtube.com/watch?v=5faA4ph4Fo8

**Comment by mailyspamy** [comment]
Yes it is possible to update even over Microsoft servers, but you have to install some updates manually and after that it will be opened the pandora box with thousends of updates, which I do not want.
I am happy with not updated system, the system is so much more responsive.
Do you know which KB... are needed to use btrfs? This I can try to install manually and stil have much more responsive system.

**Comment by maharmstone** [comment]
Which is fair enough.

I _think_ it's KB3004394 (https://support.microsoft.com/en-gb/topic/support-for-urgent-trusted-root-updates-for-windows-root-certificate-program-in-windows-a4ac4d6c-7c62-3b6e-dfd2-377982bf3ea5). Let me know if that fixes it, and I'll put it in the README.

**Comment by mailyspamy** [comment]
Nope does not help. Only version 1.0 installs drivers propperly.
![image](https://user-images.githubusercontent.com/25592998/221678982-ce088fbf-0b5a-421c-80b0-417863c3ace1.png)
At versions bigger 1.0 there is only one device (Btrfs controller) with yellow exclamation mark.
At 1.0 is found the drive in This PC, but not possible to open.
And windows still told, that drivers are not signed.
![image](https://user-images.githubusercontent.com/25592998/221679292-b2079592-78a6-42b5-a62e-ac509c80c266.png)
I tried also the 1.8.1 version, and the same behaviour.
KB3004394 installed.

**Comment by maharmstone** [comment]
I've messed around, and not been able to get any version of the driver working on 64-bit Windows 7. You're probably out of luck for now. Presumably there's also another Windows patch required, but I've no idea which one.

**Comment by maharmstone** [comment]
I've been able to install version 1.8.2 on a clean installation using this ISO: https://download.microsoft.com/download/0/6/3/06365375-C346-4D65-87C7-EE41F55F736B/7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_PROFESSIONAL_x64FRE_en-us.iso

**Comment by mailyspamy** [comment]
Hmm interesting, I searched what kind of iso it is, and it should be some pre release version.
I have normal SP1 iso installed, and should be the same.
I can install it, but I do not know if my key will be ok with this escrow version.

**Comment by mailyspamy** [comment]
OK it works with my old windows 7 instalation, certificates were old. Yesterday I write what has to be done. For now I have only three words. "fuck you microsoft"

**Comment by maharmstone** [comment]
They don't make it easy, do they?

I'm glad we were able to sort this. I've added a bit to the README about Windows 7. If I discover the exact KB numbers needed, I'll add those in too.

**Comment by mailyspamy** [comment]
Do not close the ticket, I know the KBs. After I will be back from work I
write it to the ticket.

středa 1. března 2023 maharmstone ***@***.***> napsal(a):

**Comment by ale5000-git** [comment]
I'm not sure but maybe this is needed: https://www.sevenforums.com/news/420866-kb4474419-sha-2-code-signing-support-update-windows-7-sept-10-a.html

**Comment by maharmstone** [comment]
Thanks @mailyspamy. The necessary patch turned out to actually be KB3033929, which is rolled into KB3191566. I've updated the README.

**Comment by AmitRanaware47** [comment]
------------
on windows 7 x64 Ultimate( without any updates) and WinBtrfs 1.8.1 , it worked (f**k all microsoft serial packs and updates)
---------

Part 1 

when starting pc( powering on PC ) keep pressing F8 when Windows 7 is loading and select " Disable Driver Signature Enforcement "

this will let you install unsigned drivers but when you boot normally , the driver wont work so you have to boot with "Disable Driver Signature Enforcement" everytime .

----------

Part 2

while in "Disable Driver Signature Enforcement" mode after signing winbtrfs 1.8.1

Using Driver Signature Enforcement Overrider

Download the application from the Softpedia link.
---------
Link : https://www.softpedia.com/get/Tweak/Video-Tweak/Driver-Signature-Enforcement-Overrider.shtml
---------
file name : dseo13b.exe
------------------------


Right click on it and choose "Run as administrator". Inside its main menu, press on the “Enable Test Mode” button and follow the instructions on the screen. This will enable TESTSIGNING mode, which allows unverified system files to be loaded.

Now all you have to do is to add the unverified signature to the required system files. To do so press on the “Sign a System File” button from the main menu, and enter specific filename including full path. For example: if ATITool64.sys from C:\Windows\System32\drivers refuses to load due to driver signature enforcement, you should type: C:\Windows\System32\drivers\ATITool64.sys, and if you would like to sign more than a single file, just repeat this procedure until you’re done, and finally reboot.

After you enabled Test Mode and added signatures to the required system files, they should bypass Windows’s driver signature enforcement and load without any issues. However, if for some reason you are interested to revert it, you can re-launch the application, choose “Disable Test Mode” from the main menu, and reboot.

----------

after this winbtrfs 1.8.1 works even if " Disable Driver Signature Enforcement " is not turned on

if this dont works then i might had miss some steps to write....

thanks to 
https://superuser.com/questions/1233615/how-to-force-windows-7-to-disable-driver-signature-enforcement
![Uploading btrfs1.8.1.jpg…]()
