### ISSUE TITLE
Random NO_MORE_IRP_STACK_LOCATIONS or System_Thread_Exception_not_handled BSODs caused by btrfs.sys

### ISSUE THREAD

**Issue by TheWinHelper** [maharmstone/btrfs#578]
The drivers causes random bluescreens for me. These sometimes happen during normal usage, but tend to specifically happen when taking the device out of standby. BSOD is either NO_MORE_IRP_STACK_LOCATIONS or System_Thread_Exception_not_handled. They are always caused by the btrfs.sys driver. 

System is a Thinkpad E15 G4 with an 5425U. Windows Version is Windows 11 22H2 (22624.1546). The BTRFS Drive has been formated under openSuse with gparted.

Any ideas what might cause this?

I'll attach the minidumps.
[Minidums_BTRFS_BSOD.zip](https://github.com/maharmstone/btrfs/files/11956608/Minidums_BTRFS_BSOD.zip)

**Comment by maharmstone** [comment]
Thanks for this.

The STATUS_ACCESS_VIOLATION crash is at: https://github.com/maharmstone/btrfs/blob/master/src/read.c#L2602
The NO_MORE_IRP_STACK_LOCATIONS crash is at: https://github.com/maharmstone/btrfs/blob/master/src/search.c#L542

Both of which appear to be caused by memory corruption in kernel memory.

You're using a pre-release version of Windows, which I don't support, so I'm not going to do any more digging - it might well be caused by a new kernel bug, as has happened before. If I were you I'd also run memtest to check that your RAM is sound.
