### ISSUE TITLE
Trouble with VHD(x) images and ramdrive

### ISSUE THREAD

**Issue by EdoaLive** [maharmstone/btrfs#74]
Hi
I was very excited to find again this project and to discover it became stable (and faster than NTFS!)
But my first tryouts didn't go so well (version 1.0.1 prebuilt - Windows 1709)

First thing I tried is to format my ramdisk. After some trouble with commands I did it. Now I have a ramdisk no more. Plus I got a BSOD (PNP_DETECTED_FATAL_ERROR) on reboot (I was also playing with NoPNP flag). Now I can't anymore see my ramdrive also if I try to reboot, delete and recreate it, reformat it (ntfs). The drive letter does not appear on explorer anymore.
(it's a radeon ramdisk, free edition, if you want to try: http://www.radeonramdisk.com/software_downloads.php )

Second try was using an attached vhdx. Results was pretty the same: after formatting it, the drive disappeared, if i detach and reattach the vhdx, it stop working as soon as I try to assign a letter (online the volume). 

It's just me or any other of you is having similar problems? 
Is there a way to manage/check drive letters / mount points?

BTW, i tried it on an USB dongle and it worked well, well... until I had to safely eject it.

**Comment by maharmstone** [comment]
Can you send me the minidump of the BSOD please, or recreate it if it didn't generate one? I've not encountered any of the problems you list, and I'm interested to know what's causing them.

You shouldn't have reason to turn on NoPNP unless you're working on the source code. Do the same things happen with it turned off?

**Comment by Edwin-Edward** [comment]
I turned on NoPNP because I thought it was causing problem with letter assignment. I'll send you the minidump. 
So are you saying that you have no troubles at all using WinBtrfs on vhdx images, and that letter assignment in diskpart/disk management console does work well?
I was just playing so I did not take trace of all operations I did, I'll take some time to recreate a list of operations that took me to these problems.
