### ISSUE TITLE
Changing assigned drive letter

### ISSUE THREAD

**Issue by kanchudeep** [maharmstone/btrfs#82]
The drivers work well, however while installing it due to some external storage devices being connected, the second partition (`btrfs`) was assigned `F:`.

Any way to change this (reassign the drive letter)? I'd be comfortable with making changes in the registry also if required (I went through the registry also thinking it could be there).

**Note**: I uninstalled the controller and volume, to let it again get installed but same letter was re-assigned.

**Comment by eimiss** [comment]
Try https://www.lifewire.com/how-to-change-a-drive-letter-2626069

**Comment by maharmstone** [comment]
@jdunn0, I'm not sure that's quite right. I think mountvol only lets you create directory mount points, which are really just fancy symlinks. 

@kanchudeep, the registry keys are in HKEY_LOCAL_MACHINE\System\MountedDevices, if you want to give it a go. I do intend at some point to put a thing in the shell extension to make changing drive letters easy. As I'm sure you've found out yourself, all the guides online rely on diskmgmt.msc, which doesn't like Btrfs.

**Comment by kanchudeep** [comment]
Thank you @maharmstone ... Will check it...

**Comment by jdunn0** [comment]
@maharmstone: I have used mountvol myself to point many volumes (including btrfs formatted ones) to different drive letters and mount points. It works quite well.
If you use mountvol with a drive letter, the registry location you listed will be updated.
If you use mountvol with a mount point, then an [NTFS Reparse Point](https://en.wikipedia.org/wiki/NTFS_reparse_point) will be created on the file system to point to the volume.

Also "NTFS Reparse Points" to not "just fancy symlinks", they are empty directories that hold metadata specifying the type of reparse point the empy directory is along with a volume path (to make a Mount Point) or file system path (to make a Junction or Directory Symlink) that queries to the empty directory should actually go to.
The mount point type will work the same way as drive letters to applications that are designed to handle mount points.
For example I could use mountvol to put a NTFS volume at `C:\myntfsvolume` and running the command `chkdsk C:\myntfsvolume` would do a disk check on that volume.
Should the btrfsck tool be ported to Windows then it would likely work the same way and allow a btrfs volume mounted at `C:\mybtrfsvolume` to be checked by running `btrfsck C:\mybtrfsvolume`.

WinBTRFS implements support for Reparse Points too so they are no longer an NTFS only feature.
Support is implemented by using extended attributes in the btrfs file system to store the Reparse Point information in an empty directory.
This does have the unfortunate side-effect that Directory Symlinks created on the btrfs volume in Windows appear as empty directories when viewed in a *nix Operating System instead of actual symlinks.
